//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Station.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Schedule()
        {
            this.tbl_Booking = new HashSet<tbl_Booking>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FromStationId { get; set; }
        public Nullable<int> ToStationId { get; set; }
        public Nullable<System.TimeSpan> TripTime { get; set; }
        public Nullable<double> TtripCost { get; set; }
        public Nullable<int> TripStatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Booking> tbl_Booking { get; set; }
    }
}
