//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Station.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TripStatus
    {
        public int Id { get; set; }
        public string TripStatus { get; set; }
    }
}
