//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Station.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Booking
    {
        public int Id { get; set; }
        public Nullable<int> BookingRef { get; set; }
        public Nullable<int> tripId { get; set; }
        public Nullable<int> PassengerId { get; set; }
        public Nullable<System.DateTime> RegistDate { get; set; }
        public Nullable<int> BookStatus { get; set; }
        public Nullable<System.DateTime> TravelDate { get; set; }
    
        public virtual tbl_Passengers tbl_Passengers { get; set; }
        public virtual tbl_Schedule tbl_Schedule { get; set; }
    }
}
